# Generated by Django 3.2.25 on 2026-03-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20260325_1549'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userimagepredictionmodel',
            table='UserStressImageResults',
        ),
    ]
