# Generated by Django 3.2.25 on 2026-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userimagepredictionmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
