# Generated by Django 3.2.25 on 2026-04-11 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20260411_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
